# Generated by Django 2.0.2 on 2018-02-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='sunject',
            new_name='subject',
        ),
    ]
