# Generated by Django 2.0.1 on 2018-02-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='subject',
        ),
    ]
